
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "fettlol-utilmod"
  description = "Various tweaks and integrations for the fettlol modpack."
  version = "1.3.4"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/FettLol/fettlol-utilmod"
  homepage = "https://github.com/FettLol/fettlol-utilmod"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "^1.18.2"
  fabricLoader = "^0.14.7"

[dependencies]
  cloth-config = "^6.1"
  fabric = "*"
  fettlol-lib = "^1.1.6"

[dev]
  buildCommand = "./gradlew build"
