
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "fettlol-utilmod"
  description = "Various tweaks and integrations for the fettlol modpack."
  version = "1.2.1"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/FettLol/FettLolUtilMod"
  homepage = "https://github.com/FettLol/FettLolUtilMod"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = ">=1.17.1"
  fabricLoader = ">=0.12.3"

[dependencies]
  cloth-config = "^5.0.34-0.mpkg.1"
  fabric = "*"
  fettlol-lib = "^1.0.7"

[dev]
  buildCommand = "./gradlew build"

  [dev.dependencies]
    test-mansion = "*"
