
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "fettlol-utilmod"
  description = "Various tweaks and integrations for the fettlol modpack."
  version = "1.1.13"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/FettLol/FettLolUtilMod"
  homepage = "https://github.com/FettLol/FettLolUtilMod"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = ">=1.17"
  fabricLoader = ">=0.11.0"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"

  [dev.dependencies]
    test-mansion = "*"
